export const DEFAULT_JOURNAL_PROMPTS = [
  { question: "What is one small victory you achieved today that you are proud of?", category: "gratitude" },
  { question: "What was the most challenging decision you made today and what did it teach you?", category: "growth" },
  { question: "What are three specific things you are genuinely grateful for right now?", category: "gratitude" },
  { question: "How did you bring focus and heartfelt presence to your prayers and worship today?", category: "deen" },
  { question: "What is one disciplined habit or action that propelled your progress today?", category: "productivity" },
  { question: "Who did you connect with or help today, and how did it impact you?", category: "relationships" },
  { question: "What is one thing you can do tomorrow to make your life 1% easier or better?", category: "growth" },
  { question: "What primary intention (Niyyah) do you want to anchor tomorrow around?", category: "deen" },
  { question: "If you could redo one moment from today with more calm, what would it be?", category: "mindset" },
  { question: "What drained your energy today, and how can you protect your boundaries tomorrow?", category: "mindset" },
  { question: "What did you learn today about your own strengths or blind spots?", category: "growth" },
  { question: "How did you handle unexpected disruptions or stress today?", category: "discipline" },
  { question: "What is a blessing in your life that you frequently take for granted?", category: "gratitude" },
  { question: "Which core value did your actions reflect most clearly today?", category: "mindset" },
  { question: "What physical sensation or emotion did you notice most in your body today?", category: "mindset" },
  { question: "What is one piece of knowledge, skill, or wisdom you acquired today?", category: "growth" },
  { question: "In what way did you invest in your long-term health or fitness today?", category: "productivity" },
  { question: "How did you practice patience or forgiveness with someone today?", category: "relationships" },
  { question: "What is a Quranic verse or Hadith that resonated with your heart today?", category: "deen" },
  { question: "What is the single most important task you must complete first tomorrow?", category: "productivity" },
  { question: "Where did you step out of your comfort zone today?", category: "growth" },
  { question: "How did you manage your digital distractions and screen time today?", category: "discipline" },
  { question: "What made you smile or laugh today?", category: "gratitude" },
  { question: "What is one self-limiting belief you noticed yourself having today, and how can you reframe it?", category: "mindset" },
  { question: "How did your financial decisions today align with your long-term life vision?", category: "discipline" },
  { question: "What did you do today simply for the joy and satisfaction of doing it?", category: "gratitude" },
  { question: "What is one conversation you had today that gave you clarity?", category: "relationships" },
  { question: "How did you show kindness to yourself during a difficult moment today?", category: "mindset" },
  { question: "What standard or habit did you hold yourself to even when you did not feel like it?", category: "discipline" },
  { question: "If today was a chapter in your autobiography, what would its title be?", category: "growth" },
];

